name: Lint changed lines

on:
  push:
    branches:
      - test2

jobs:
  lint_changed_lines:
    name: runner / retext-style-guide
    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: test2
          fetch-depth: 0

      - uses: ./.github/actions/retext-style-guide
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
          filter_mode: added
          diff: git diff --unified=0 ${{ github.event.before }} ${{ github.sha }} | grep '^\+' | sed 's/^+//' | grep -v '^\+\+\+' | sed 's/:[[:digit:]]\+:.*//' | uniq
