name: Lint changed lines

on:
  push:
    branches:
      - test

jobs:
  lint_changed_lines:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: test
          fetch-depth: 0

      - name: Upgrade npm to latest version
        run: npm install -g npm@latest

      - name: Print npm version
        run: npm --version

      - name: Install Node.js
        uses: actions/setup-node@v4

      - name: Install dependencies
        run: npm install -g

      - name: Get changed lines
        id: get_changed_lines
        run: |
          CHANGED_LINES=$(git diff --unified=0 ${{ github.event.before }} ${{ github.sha }} | grep '^\+' | sed 's/^+//' | grep -v '^\+\+\+' | sed 's/:[[:digit:]]\+:.*//' | uniq)
          echo "Value of changed lines: ${CHANGED_LINES}"
          echo "${CHANGED_LINES}" >> file1.md

      - name: View contents of file1.md
        run: cat file1.md

      - name: Set executable permission on lint.sh
        run: |
          chmod +x lint.sh
          ls -l lint.sh
        
      - name: Run linting script
        run: ./lint.sh



# name: remark
# on: [pull_request]
# jobs:
#   remark:
#     name: runner / retext-style-guide
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v3
#       - uses: ./.github/actions/retext-style-guide
#         with:
#           github_token: ${{ secrets.GITHUB_TOKEN }}
#           reporter: github-pr-review
#           filter_mode: added