name: Lint changed lines

on:
  push:
    branches:
      - test

jobs:
  lint_changed_lines:
    runs-on: ubuntu-latest

    env:
      BEFORE_COMMIT: ${{ github.event.before }}
      AFTER_COMMIT: ${{ github.sha }}

    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Upgrade npm to latest version
        run: npm install -g npm@latest

      - name: Print npm version
        run: npm --version

      - name: Install Node.js
        uses: actions/setup-node@v4

      - name: Install dependencies
        run: npm install

      - name: Get changed lines
        id: get_changed_lines
        run: |
          echo "${BEFORE_COMMIT} and ${AFTER_COMMIT}"
          CHANGED_LINES=$(git diff --unified=0 f279843372df9bb16931860c982f97c0bf23431d bba786882ef4c995026fd0f076fa56d1e6aff8a3 | grep '^\+' | sed 's/^+//' | grep -v '^\+\+\+' | sed 's/:[[:digit:]]\+:.*//' | uniq)
          echo "Value of changed lines: ${CHANGED_LINES}"
          echo "CHANGED=${CHANGED_LINES}" >> $GITHUB_ENV

      - name: Load changed lines from environment file
        run: |
          echo "Value of CHANGED: $CHANGED"
#         echo "$CHANGED" | xargs npx remark --use remark-lint




# name: remark
# on: [pull_request]
# jobs:
#   remark:
#     name: runner / retext-style-guide
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v3
#       - uses: ./.github/actions/retext-style-guide
#         with:
#           github_token: ${{ secrets.GITHUB_TOKEN }}
#           reporter: github-pr-review
#           filter_mode: added